apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: aws-secretsmanager
  namespace: online-boutique
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-west-2
      auth:
        jwt:
          serviceAccountRef:
            name: cartservice
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cartservice-demo-secret
  namespace: online-boutique
spec:
  secretStoreRef:
    name: aws-secretsmanager
    kind: SecretStore
  target:
    name: cartservice-demo-secret
  data:
    - secretKey: demo_key
      remoteRef:
        key: online-boutique/cartservice/demo-credential
        property: demo_key
